export const GET_SONGS_LIST = "GET_SONGS_LIST";
export const GET_SONGS_LIST_SUCCESS = "GET_SONGS_LIST_SUCCESS";

export const GET_SONGS_DETAILS = "GET_SONGS_DETAILS";
export const GET_SONGS_DETAILS_SUCCESS = "GET_SONGS_DETAILS_SUCCESS";

export const GET_SUGGESTED_SONGS = "GET_SUGGESTED_SONGS";
export const GET_SUGGESTED_SONGS_SUCCESS = "GET_SUGGESTED_SONGS_SUCCESS";

export const TOGGLE_PAUSE = "TOGGLE_PAUSE";
export const SET_SOUND_OBJECT = "SET_SOUND_OBJECT";
export const SET_CURRENT_SONG = "SET_CURRENT_SONG";

export const UPDATE_PLAY_INDEX = "UPDATE_PLAY_INDEX";

export const REMOVE_SONG_FROM_SUGGESTIONS = "REMOVE_SONG_FROM_SUGGESTIONS";
export const ADD_SONG_TO_SUGGESTIONS = "ADD_SONG_TO_SUGGESTIONS";
